### ISSUE TITLE
日历热力图月份显示混乱，有重复和缺失月份

### ISSUE THREAD

**Issue by jiangzhujun** [svtardust/Calendar-heatmap#40]
![image](https://github.com/svtardust/Calendar-heatmap/assets/52827653/8b1be197-05fa-495a-a49e-44e24dcb4515)
作者你好！感谢您写出这么好的插件，非常方便实用。我遇到的问题如下：
如上图所示，热力图从左至右起缺失22年10月、23年1月、23年3月、23年5月、23年8月的统计；重复了22年11月、23年2月、23年4月、23年6月、23年8月的统计。重复的月份鼠标放上去显示确实是重复的那个月份的数据，不是单纯的顶部月份显示错误。在昨天之前都还是正常显示，有8月份的统计信息。我用的是思源原生主题。

**Comment by svtardust** [comment]
![image](https://github.com/svtardust/Calendar-heatmap/assets/132273422/a5d2b3a1-7bb8-42ed-b2e6-516c28fb8722)

奇怪，我这没问题呀，这样我也定位不到问题，是最新版本吗？
要不把其他插件暂时关掉，看看是不是跟某个插件冲突？

**Comment by svtardust** [comment]
好吧，我大概知道原因了，公立年的大月的最后一天，也就是有31天的月份的最后一天，当时间走到最后这一天时也就是31号统计会混乱，具体为啥我没搞懂

**Comment by jiangzhujun** [comment]
感谢！我这里也是只在31号能复现出来这个问题
