### ISSUE TITLE
用一段时候后不显示热力块了

### ISSUE THREAD

**Issue by JOKer-2333** [svtardust/Calendar-heatmap#42]
如图今天写了些内容块，但热力图上没有表现。
![Snipaste_2023-10-03_16-39-40](https://github.com/svtardust/Calendar-heatmap/assets/53433857/af57baac-c6b5-4a72-9be4-cd6e36a81411)

**Comment by svtardust** [comment]
你好，可以看下是否把文本忽略了？
![image](https://github.com/svtardust/Calendar-heatmap/assets/132273422/9f36f5f0-1ff6-4ea2-b9dd-503a924065c1)

**Comment by svtardust** [comment]
ok，找到了，是个bug
