### ISSUE TITLE
统计数据存在问题

### ISSUE THREAD

**Issue by Dandy-John** [svtardust/Calendar-heatmap#45]
![image](https://github.com/svtardust/Calendar-heatmap/assets/17698785/e8fa1df7-7a67-4338-87d8-463f7834f807)
当天写了一些文档，下方统计也有区块新增，但是热力图当日为0改动，网页端和客户端重启均未恢复正常
网页端客户端版本为2.11.1，插件版本1.0.20

**Comment by svtardust** [comment]
热力图设置里有把该文件忽略吗？

**Comment by Dandy-John** [comment]
文件忽略没设置过，是空的

**Comment by Simuliya** [comment]
> 热力图设置里有把该文件忽略吗？

我也出现了这个问题,没有设置过文件忽略

**Comment by svtardust** [comment]
> > 热力图设置里有把该文件忽略吗？
> 
> 我也出现了这个问题,没有设置过文件忽略,但是第二天的是正常的,只有那一天热力图颜色是空的,大概改了70个内容块

日期给我，我看看吧

**Comment by AvoidantPerDis** [comment]
2.10
遇到了同样的问题

**Comment by AvoidantPerDis** [comment]
![image](https://github.com/svtardust/Calendar-heatmap/assets/154863885/8cfbb8b3-0ee6-493b-8229-6a9e54870f0b)
还有12月10号。我每天都会记日记，应该不存在为0的情况

**Comment by Simuliya** [comment]
> > > 热力图设置里有把该文件忽略吗？
> > 
> > 
> > 我也出现了这个问题,没有设置过文件忽略,但是第二天的是正常的,只有那一天热力图颜色是空的,大概改了70个内容块
> 
> 日期给我，我看看吧

![image](https://github.com/svtardust/Calendar-heatmap/assets/127732514/354681a8-ff4e-44b9-911a-455d82808263)
同2-10,只在win端操作了

**Comment by AvoidantPerDis** [comment]
![image](https://github.com/svtardust/Calendar-heatmap/assets/154863885/f1a0917f-0f0f-4105-b30a-1230e7f4c0dc)
补个1.10，可能真是十号有问题

**Comment by AvoidantPerDis** [comment]
只统计 daily note 也统计不到十号的
